class ErrorCode:
    ERR_UNAUTHORIZED = "UNAUTHORIZED"
    ERR_ACCESS_DENIED = "ACCESS_DENIED"
    ERR_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    ERR_TOKEN_EXPIRED = "TOKEN_EXPIRED"
    ERR_INVALID_TOKEN = "INVALID_TOKEN"
    ERR_USER_ALREADY_EXISTED = "ERR_USER_ALREADY_EXISTED"
    ERR_PASSWORD_NOT_MATCHING = "ERR_PASSWORD_NOT_MATCHING"
    ERR_TAG_NOT_FOUND = "ERR_TAG_NOT_FOUND"


class ErrorMessage:
    ERR_UNAUTHORIZED = "Unauthorized"
    ERR_PASSWORD_NOT_MATCHING = "The password and confirmation password do not match."
    ERR_TOKEN_EXPIRED = "The token was expired."
    ERR_USER_ALREADY_EXISTED = "This account already existed."
    ERR_INVALID_TOKEN = "Invalid token."
