class ErrorCode:
    ERR_UNAUTHORIZED = "UNAUTHORIZED"
    ERR_ACCESS_DENIED = "ACCESS_DENIED"
    ERR_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    ERR_TOKEN_EXPIRED = "TOKEN_EXPIRED"
    ERR_INVALID_TOKEN = "INVALID_TOKEN"


class ErrorMessage:
    ERR_UNAUTHORIZED = "Unauthorized"
