events{}
http{
  server_tokens off;
  
  server {
    listen 80;
    listen [::]:80;
    server_name vievent.site www.vievent.site;

    location ~ /.well-known/acme-challenge/{
      root /var/www/certbot;
    }

    return 301 https://$host$request_uri/;

  }

  server{
    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/vievent.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vievent.site/privkey.pem;
    server_name vievent.site;

    root /var/www/html;

    location / {
      proxy_pass http://localhost:3000/;
      proxy_read_timeout 300;
    }

    location ~ /.well-known/acme-challenge/{
      root /var/www/certbot;
    }
  }

  server {
    listen [::]:443 ssl;
    listen 443 ssl;

    ssl_certificate /etc/letsencrypt/live/api.vievent.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.vievent.site/privkey.pem;

    server_name api.vievent.site;

    location / {
      proxy_pass http://localhost:8000/;
      proxy_set_header Host $host;

      add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
      add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization' always;
      add_header 'Access-Control-Allow-Credentials' 'true' always;

    }
  }
}