export const INDUSTRY_CODES: { [key: string]: string } = {
	REAL_ESTATE: 'Real Estate',
	CONSTRUCTION: 'Construction',
	FOOD_DRINK: 'Food & Drink',
	COSMETICS_MANUFACTURING: 'Cosmetics Manufacturing',
	ELECTRONICS_MANUFACTURING: 'Electronics Manufacturing',
	PRECISION_MANUFACTURING: 'Precision Manufacturing',
	AUTOMOTIVE_MANUFACTURING: 'Automotive Manufacturing',
	FASHION_MANUFACTURING: 'Fashion Manufacturing',
	B2C_MANUFACTURING: 'B2C Manufacturing',
	B2B_MANUFACTURING: 'B2B Manufacturing',
	LOGISTICS: 'Logistics',
	IT_COMMUNICATIONS: 'IT & Communications',
	CONTRACT_DEVELOPMENT: 'Contract Development',
	RETAIL: 'Retail',
	WHOLESALE: 'Wholesale',
	FINANCE: 'Finance',
	HOSPITALITY: 'Hospitality',
	CONSULTING: 'Consulting',
	HEALTHCARE: 'Healthcare',
	ADVERTISING: 'Advertising',
	ENTERTAINMENT: 'Entertainment',
	EDUCATION: 'Education',
	MEDIA: 'Media',
	MINING: 'Mining',
	TRANSPORTATION: 'Transportation',
	WAREHOUSING: 'Warehousing',
	CHEMICAL: 'Chemical',
	OTHER: 'Other',
};
