version: "3.8"

services:
  app:
    container_name: roominar-app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspace:cached

    ports:
      - 8000:8000

      # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db

    depends_on:
      - db
    # networks:
    #   - service:db
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    env_file:
      - ../backend/.env

  db:
    image: postgres:latest
    container_name: roominar-db
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  stripe:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: listen --forward-to http://app:8000/api/v1/transactions/webhook
    depends_on:
      - app
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_DEVICE_NAME=${STRIPE_DEVICE_NAME}

volumes:
  postgres-data:

networks:
  default:
    name: roominar-network
