services:
  app:
    container_name: roominar-app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspace:cached
    ports:
      - 2001:2001 # Backend (uvicorn, FastAPI...)
      - 2002:2002 # Frontend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ../backend/.env

  db:
    image: postgres:latest
    container_name: roominar-db
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 2003:5432 # đổi từ 5432

  stripe:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: listen --forward-to http://app:2001/api/v1/transactions/webhook # đổi từ 8000
    depends_on:
      - app
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_DEVICE_NAME=${STRIPE_DEVICE_NAME}

  redis:
    image: redis:latest
    container_name: roominar-redis
    ports:
      - 2006:6379 # đổi từ 6379

  celery_worker:
    container_name: roominar-celery
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: roominar-celery
    working_dir: /workspace/Roominar
    command: poetry run celery -A backend.celery worker --loglevel=info
    volumes:
      - ../..:/workspace:cached
    depends_on:
      - app
      - redis
    restart: unless-stopped

  celery_beat:
    container_name: roominar-celery-beat
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: roominar-celery-beat
    working_dir: /workspace/Roominar
    command: poetry run celery -A backend.celery beat --loglevel=info
    volumes:
      - ../..:/workspace:cached
    depends_on:
      - app
      - redis
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  default:
    name: roominar-network
