"""Migrate all model

Revision ID: 1d057fa5d913
Revises:
Create Date: 2024-08-29 17:00:57.388908

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d057fa5d913"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("hp_url", sa.String(length=2048), nullable=True),
        sa.Column("city_code", sa.String(length=50), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="orgstatuscode"),
            nullable=False,
        ),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("plan_code", sa.String(length=20), nullable=True),
        sa.Column("contact_url", sa.String(length=2048), nullable=True),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("facebook_url", sa.String(length=2048), nullable=True),
        sa.Column("remarks", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tag_groups",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "questionnaires",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "status_code",
            sa.Enum("OPEN", "ARCHIVE", name="questionnairestatuscode"),
            nullable=True,
        ),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("image_url", sa.String(length=2048), nullable=True),
        sa.Column("tag_group_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "targets",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("industry_codes", sa.ARRAY(sa.String(length=50)), nullable=True),
        sa.Column("job_type_codes", sa.ARRAY(sa.String(length=50)), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column(
            "role_code",
            sa.Enum("AUDIENCE", "SPEAKER", "ORGANIZER", "ADMIN", name="rolecode"),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("workplace_name", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("city_code", sa.String(length=50), nullable=True),
        sa.Column(
            "industry_code",
            sa.Enum(
                "REAL_ESTATE",
                "CONSTRUCTION",
                "FOOD_DRINK",
                "COSMETICS_MANUFACTURING",
                "ELECTRONICS_MANUFACTURING",
                "PRECISION_MANUFACTURING",
                "AUTOMOTIVE_MANUFACTURING",
                "FASHION_MANUFACTURING",
                "B2C_MANUFACTURING",
                "B2B_MANUFACTURING",
                "LOGISTICS",
                "IT_COMMUNICATIONS",
                "CONTRACT_DEVELOPMENT",
                "RETAIL",
                "WHOLESALE",
                "FINANCE",
                "HOSPITALITY",
                "CONSULTING",
                "HEALTHCARE",
                "ADVERTISING",
                "ENTERTAINMENT",
                "EDUCATION",
                "MEDIA",
                "MINING",
                "TRANSPORTATION",
                "WAREHOUSING",
                "CHEMICAL",
                "OTHER",
                name="industrycode",
            ),
            nullable=True,
        ),
        sa.Column(
            "job_type_code",
            sa.Enum(
                "DEV",
                "QA",
                "PM",
                "TESTER",
                "SYSADMIN",
                "DBA",
                "SA",
                "ACC",
                "FIN",
                "CFA",
                "TAX",
                "AUD",
                "SEO",
                "SMM",
                "PR",
                "AD",
                "CMM",
                "TEACHER",
                "LECTURER",
                "TUTOR",
                "PRINCIPAL",
                "COUNSELOR",
                "DOCTOR",
                "NURSE",
                "PHARM",
                "SURGEON",
                "THER",
                "ARCH",
                "ENG",
                "CIVIL",
                "CON",
                "QS",
                "DESIGNER",
                "ARTIST",
                "WRITER",
                "MUSICIAN",
                "ACTOR",
                "CS",
                "SALES",
                "CRM",
                "CASHIER",
                "MERCH",
                "DRIVER",
                "LOG",
                "WAREHOUSE",
                "SHIP",
                "FARMER",
                "AGR",
                "VET",
                "HORT",
                name="jobtypecode",
            ),
            nullable=True,
        ),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column("email_verify_token", sa.String(length=2048), nullable=True),
        sa.Column(
            "email_verify_token_expire_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("email_verify_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reset_password_token", sa.String(length=2048), nullable=True),
        sa.Column(
            "reset_password_token_expire_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("change_password_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("new_email", sa.String(length=255), nullable=True),
        sa.Column("new_email_verify_token", sa.String(length=2048), nullable=True),
        sa.Column(
            "new_email_verify_token_expire_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=1024), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("application_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("application_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "slug",
            sa.String(length=36),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PUBLIC", "DRAFT", "PRIVATE", name="eventstatuscode"),
            nullable=True,
        ),
        sa.Column("application_number", sa.Integer(), nullable=True),
        sa.Column("cover_image_url", sa.String(length=2048), nullable=True),
        sa.Column("gallery", sa.ARRAY(sa.String(length=2048)), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_online", sa.Boolean(), nullable=True),
        sa.Column("is_offline", sa.Boolean(), nullable=True),
        sa.Column("organize_place_name", sa.String(length=255), nullable=True),
        sa.Column("organize_city_code", sa.String(length=50), nullable=True),
        sa.Column("organize_address", sa.String(length=255), nullable=True),
        sa.Column(
            "meeting_tool_code",
            sa.Enum(
                "ZOOM",
                "GOOGLE_MEET",
                "DISCORD",
                "ROOMINAR",
                "OTHER",
                "CONTACT_LATER",
                name="eventmeetingtoolcode",
            ),
            nullable=True,
        ),
        sa.Column("meeting_url", sa.String(length=2048), nullable=True),
        sa.Column("questionnaire_id", sa.Integer(), nullable=True),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String(length=255)), nullable=True),
        sa.Column("public_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("application_form_url", sa.String(length=2048), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("questionnaire_id", sa.Integer(), nullable=False),
        sa.Column(
            "type_code",
            sa.Enum("SINGLE", "MULTIPLE", name="questiontypecode"),
            nullable=False,
        ),
        sa.Column("question", sa.String(length=1024), nullable=False),
        sa.Column("order_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_tags",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "answers",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("questionnaire_id", sa.Integer(), nullable=False),
        sa.Column("answer", sa.String(length=1024), nullable=False),
        sa.Column("order_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bookmarks",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_tags",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "EARLY_BIRD",
                "VIP",
                "GROUP",
                "CORPORATE",
                "STUDENT",
                "FREE",
                "DONATION",
                "MULTIDAY",
                "DAY_PASS",
                name="tickettypecode",
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("AVAILABLE", "SOLD_OUT", "CANCELED", name="ticketstatuscode"),
            nullable=True,
        ),
        sa.Column("sales_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sales_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "delivery_method",
            sa.Enum("ONLINE", "OFFLINE", "BOTH", name="ticketdeliverymethodcode"),
            nullable=True,
        ),
        sa.Column("access_link_url", sa.String(length=2048), nullable=True),
        sa.Column("is_refundable", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "applications",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("workplace_name", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", "CANCELED", name="applicationstatuscode"),
            nullable=True,
        ),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "question_answer_results",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("questionnaire_id", sa.Integer(), nullable=False),
        sa.Column("answers_ids", sa.ARRAY(sa.Integer()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question_answer_results")
    op.drop_table("applications")
    op.drop_table("tickets")
    op.drop_table("event_tags")
    op.drop_table("bookmarks")
    op.drop_table("answers")
    op.drop_table("user_tags")
    op.drop_table("questions")
    op.drop_table("events")
    op.drop_table("users")
    op.drop_table("targets")
    op.drop_table("tags")
    op.drop_table("questionnaires")
    op.drop_table("tag_groups")
    op.drop_table("organizations")
    # ### end Alembic commands ###
