"""Organization Model: remove tag column

Revision ID: e50f019e9c34
Revises: 95080ba0de2b
Create Date: 2024-12-02 14:45:13.537034

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e50f019e9c34"
down_revision: Union[str, None] = "95080ba0de2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("organizations", "tags")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "organizations",
        sa.Column(
            "tags", postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True
        ),
    )

    # ### end Alembic commands ###
