"""User Model: new email token, change to ed

Revision ID: 30789ece1606
Revises: 7812c6cd7e88
Create Date: 2024-09-16 14:10:05.788752

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "30789ece1606"
down_revision: Union[str, None] = "7812c6cd7e88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "events", sa.Column("published_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_column("events", "public_at")
    op.add_column(
        "users", sa.Column("verify_email_token", sa.String(length=2048), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "verify_email_token_expire_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("users", sa.Column("old_email", sa.String(length=255), nullable=True))
    op.add_column(
        "users",
        sa.Column("verify_change_email_token", sa.String(length=2048), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "verify_change_email_token_expire_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column("email_changed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_column("users", "change_password_at")
    op.drop_column("users", "email_verify_at")
    op.drop_column("users", "email_verify_token")
    op.drop_column("users", "new_email_verify_token")
    op.drop_column("users", "new_email_verify_token_expire_at")
    op.drop_column("users", "email_verify_token_expire_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "email_verify_token_expire_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "new_email_verify_token_expire_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "new_email_verify_token",
            sa.VARCHAR(length=2048),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "email_verify_token",
            sa.VARCHAR(length=2048),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "email_verify_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "change_password_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("users", "email_changed_at")
    op.drop_column("users", "verify_change_email_token_expire_at")
    op.drop_column("users", "verify_change_email_token")
    op.drop_column("users", "old_email")
    op.drop_column("users", "password_changed_at")
    op.drop_column("users", "email_verified_at")
    op.drop_column("users", "verify_email_token_expire_at")
    op.drop_column("users", "verify_email_token")
    op.add_column(
        "events",
        sa.Column(
            "public_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("events", "published_at")
    # ### end Alembic commands ###
