"""Bigupdate: Clarify Transaction

Revision ID: edbd445f7ae4
Revises: 8f994db509f9
Create Date: 2024-12-28 03:49:01.426357

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "edbd445f7ae4"
down_revision: Union[str, None] = "8f994db509f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_items",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("refunded_amount", sa.Float(), nullable=True),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "refund_reason_code",
            sa.Enum(
                "CUSTOMER_REQUEST",
                "EVENT_CANCELED",
                "EVENT_RESCHEDULED",
                "TECHNICAL_ERROR",
                "DUPLICATE_PAYMENT",
                "POLICY_CHANGE",
                "FRAUDULENT_TRANSACTION",
                "LEGAL_ISSUE",
                name="refundreasoncode",
            ),
            nullable=True,
        ),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "check_ins",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=True),
        sa.Column("transaction_item_id", sa.Integer(), nullable=True),
        sa.Column("checkout_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "checkin_method_code",
            sa.Enum("MANUAL", "QR", "FACE", "OTHER", name="checkinmethodcode"),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "applications",
        sa.Column("transaction_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("applications", "transaction_id", server_default=None)
    op.add_column(
        "applications", sa.Column("note", sa.String(length=255), nullable=True)
    )
    op.drop_column("applications", "check_in_at")
    op.add_column(
        "transactions",
        sa.Column("event_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("transactions", "event_id", server_default=None)
    op.drop_column("transactions", "refunded_amount")
    op.drop_column("transactions", "application_id")
    op.drop_column("transactions", "ticket_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("ticket_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "transactions",
        sa.Column("application_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "refunded_amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("transactions", "event_id")
    op.add_column(
        "applications",
        sa.Column(
            "check_in_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("applications", "note")
    op.drop_column("applications", "transaction_id")
    op.drop_table("check_ins")
    op.drop_table("transaction_items")
    # ### end Alembic commands ###
