"""Base user and org model

Revision ID: b0f1d0c18da3
Revises: 
Create Date: 2024-08-11 16:07:14.343917

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b0f1d0c18da3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("hp_url", sa.String(length=2048), nullable=True),
        sa.Column("city_code", sa.String(length=50), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="orgstatuscode"),
            nullable=False,
        ),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("plan_code", sa.String(length=20), nullable=True),
        sa.Column("contact_url", sa.String(length=2048), nullable=True),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("facebook_url", sa.String(length=2048), nullable=True),
        sa.Column("remarks", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column(
            "role_code",
            sa.Enum("AUDIENCE", "SPEAKER", "ORGANIZER", "ADMIN", name="rolecode"),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("workplace_name", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("city_code", sa.String(length=50), nullable=True),
        sa.Column("industry_code", sa.String(length=50), nullable=True),
        sa.Column("job_type_code", sa.String(length=20), nullable=True),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column("email_verify_token", sa.String(length=2048), nullable=True),
        sa.Column(
            "email_verify_token_expire_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("email_verify_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reset_password_token", sa.String(length=2048), nullable=True),
        sa.Column(
            "reset_password_token_expire_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("change_password_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("new_email", sa.String(length=255), nullable=True),
        sa.Column("new_email_verify_token", sa.String(length=2048), nullable=True),
        sa.Column(
            "new_email_verify_token_expire_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("organizations")
    # ### end Alembic commands ###
