"""User Model: Add login method code

Revision ID: 7812c6cd7e88
Revises: 15610f71f321
Create Date: 2024-09-15 02:40:51.601013

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7812c6cd7e88"
down_revision: Union[str, None] = "15610f71f321"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    login_method_enum = sa.Enum(
        "NORMAL", "GOOGLE", "GITHUB", "FACEBOOK", "X", name="loginmethodcode"
    )
    login_method_enum.create(op.get_bind())  # Create enum in the database

    op.add_column(
        "users",
        sa.Column(
            "login_method_code",
            sa.Enum(
                "NORMAL", "GOOGLE", "GITHUB", "FACEBOOK", "X", name="loginmethodcode"
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "login_method_code")

    # ### drop the enum type ###
    login_method_enum = sa.Enum(
        "NORMAL", "GOOGLE", "GITHUB", "FACEBOOK", "X", name="loginmethodcode"
    )
    login_method_enum.drop(op.get_bind())  # Drop enum from the database

    # ### end Alembic commands ###
