"""update: Add check-in-at field and remove tag field in event

Revision ID: 56d76ff9c176
Revises: 2b79a95e254c
Create Date: 2024-12-21 17:42:23.831489

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "56d76ff9c176"
down_revision: Union[str, None] = "2b79a95e254c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications",
        sa.Column("check_in_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.drop_column("events", "tags")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.VARCHAR(length=255)),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("applications", "check_in_at")
    # ### end Alembic commands ###
