"""Update Transaction Application id

Revision ID: 850c07e764c4
Revises: bc4099c34a20
Create Date: 2024-12-28 04:53:19.831041

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "850c07e764c4"
down_revision: Union[str, None] = "bc4099c34a20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "transaction_id")
    op.add_column(
        "ticket_inventories",
        sa.Column("event_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("ticket_inventories", "id", server_default=None)
    op.alter_column(
        "ticket_inventories",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.add_column(
        "transactions",
        sa.Column("application_id", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("transactions", "application_id", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "application_id")
    op.alter_column(
        "ticket_inventories",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("ticket_inventories", "event_id")
    op.add_column(
        "applications",
        sa.Column("transaction_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
