"""Organization Model: Add type, representative_url

Revision ID: 9e982d1a4da0
Revises: 6eb1c2df68ae
Create Date: 2024-10-01 14:49:54.073830

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e982d1a4da0"
down_revision: Union[str, None] = "6eb1c2df68ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    organization_type_enum = sa.Enum(
        "PERSONAL", "BUSINESS", "GOVERNMENT", "EDUCATION", name="organizationtypecode"
    )
    organization_type_enum.create(op.get_bind())  # Create enum in the database

    op.add_column(
        "organizations",
        sa.Column(
            "type",
            sa.Enum(
                "PERSONAL",
                "BUSINESS",
                "GOVERNMENT",
                "EDUCATION",
                name="organizationtypecode",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "organizations",
        sa.Column("representative_url", sa.String(length=2048), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("organizations", "representative_url")
    op.drop_column("organizations", "type")

    organization_type_enum = sa.Enum(
        "PERSONAL", "BUSINESS", "GOVERNMENT", "EDUCATION", name="organizationtypecode"
    )
    organization_type_enum.drop(op.get_bind())  # Drop enum from the database

    # ### end Alembic commands ###
