"""Event Model: Update event status: deffered

Revision ID: 6eb1c2df68ae
Revises: 00bca45e577c
Create Date: 2024-09-21 08:33:53.919145

"""

from typing import Sequence, Union

from alembic import op

from backend.core.constants import EventStatusCode

# revision identifiers, used by Alembic.
revision: str = "6eb1c2df68ae"
down_revision: Union[str, None] = "00bca45e577c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

enum_name = EventStatusCode.mro()[0].__name__.lower()
enum_keys_to_add = [EventStatusCode.DEFERRED.name]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for v in enum_keys_to_add:
        op.execute(f"ALTER TYPE {enum_name} ADD VALUE '{v}'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for v in enum_keys_to_add:
        sql = f"""DELETE FROM pg_enum
            WHERE enumlabel = '{v}'
            AND enumtypid = (
              SELECT oid FROM pg_type WHERE typname = '{enum_name}'
            )"""
        op.execute(sql)
    # ### end Alembic commands ###
