"""Transactin Model: remove require reference

Revision ID: 8f994db509f9
Revises: 56d76ff9c176
Create Date: 2024-12-24 16:28:14.440874

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f994db509f9"
down_revision: Union[str, None] = "56d76ff9c176"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "transactions", "reference", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint("transactions_reference_key", "transactions", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "transactions_reference_key", "transactions", ["reference"]
    )
    op.alter_column(
        "transactions", "reference", existing_type=sa.VARCHAR(), nullable=False
    )

    # ### end Alembic commands ###
