"""Transaction Model: add stripe info

Revision ID: 2b79a95e254c
Revises: 1cfbaed88b60
Create Date: 2024-12-14 18:18:15.525882

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2b79a95e254c"
down_revision: Union[str, None] = "1cfbaed88b60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "transactions", sa.Column("refunded_amount", sa.Float(), nullable=True)
    )
    op.add_column(
        "transactions",
        sa.Column(
            "stripe_payment_intent_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "stripe_checkout_session_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.add_column(
        "transactions",
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.alter_column(
        "transactions",
        "total_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "transactions",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "PURCHASED", "CANCELED", "FAILED", name="transactionstatuscode"
        ),
        nullable=False,
    )
    op.create_unique_constraint(None, "transactions", ["reference"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="unique")
    op.alter_column(
        "transactions",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "PURCHASED", "CANCELED", "FAILED", name="transactionstatuscode"
        ),
        nullable=True,
    )
    op.alter_column(
        "transactions",
        "total_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.drop_column("transactions", "reference")
    op.drop_column("transactions", "stripe_checkout_session_id")
    op.drop_column("transactions", "stripe_payment_intent_id")
    op.drop_column("transactions", "refunded_amount")
    # ### end Alembic commands ###
