"""fix: wrong datetime field

Revision ID: fb41e2e14bfd
Revises: de67bd3627f7
Create Date: 2024-10-12 03:14:07.638342

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fb41e2e14bfd"
down_revision: Union[str, None] = "de67bd3627f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "surveys", sa.Column("start_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "surveys", sa.Column("end_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_column("surveys", "end_date")
    op.drop_column("surveys", "start_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "surveys",
        sa.Column(
            "start_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "surveys",
        sa.Column(
            "end_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("surveys", "end_at")
    op.drop_column("surveys", "start_at")
    # ### end Alembic commands ###
