"""Event: Remove event place name

Revision ID: abb5e7144797
Revises: 850c07e764c4
Create Date: 2025-01-31 16:09:16.085175

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abb5e7144797"
down_revision: Union[str, None] = "850c07e764c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "organize_place_name")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "events",
        sa.Column(
            "organize_place_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )

    # ### end Alembic commands ###
