"""UserAction: Update action_type

Revision ID: 67a62c7ed2e6
Revises: aed5a087ceb9
Create Date: 2025-03-30 03:40:02.777693

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "67a62c7ed2e6"
down_revision: Union[str, None] = "aed5a087ceb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_action_type_code_enum = postgresql.ENUM(
        "VIEW",
        "BOOKMARK",
        "SHARE",
        "COMMENT",
        "FOLLOW",
        "RATE",
        "CHECK_IN",
        "CHECK_OUT",
        "PURCHASE_TICKET",
        "SEARCH",
        "DOWNLOAD",
        "UPGRADE_PLAN",
        "WATCH_VIDEO",
        "SUBMIT_SURVEY",
        "CANCEL_TICKET",
        "ADD_TO_CALENDAR",
        "INVITE_FRIEND",
        name="useractiontypecode",
        create_type=False,
    )
    user_action_type_code_enum.create(op.get_bind(), checkfirst=False)
    op.add_column(
        "user_actions",
        sa.Column(
            "action_type",
            sa.Enum(
                "VIEW",
                "BOOKMARK",
                "SHARE",
                "COMMENT",
                "FOLLOW",
                "RATE",
                "CHECK_IN",
                "CHECK_OUT",
                "PURCHASE_TICKET",
                "SEARCH",
                "DOWNLOAD",
                "UPGRADE_PLAN",
                "WATCH_VIDEO",
                "SUBMIT_SURVEY",
                "CANCEL_TICKET",
                "ADD_TO_CALENDAR",
                "INVITE_FRIEND",
                name="useractiontypecode",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_actions", "action_type")

    # ### end Alembic commands ###
