"""Event Feedback

Revision ID: b0115b35b80d
Revises: 5beb679ab998
Create Date: 2025-07-05 02:19:25.787356

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0115b35b80d"
down_revision: Union[str, None] = "5beb679ab998"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback_criteria",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feedback_criteria_event_id"),
        "feedback_criteria",
        ["event_id"],
        unique=False,
    )
    op.create_table(
        "feedback_scores",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("feedback_id", sa.Integer(), nullable=False),
        sa.Column("criteria_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "feedback_id", "criteria_id", name="uix_feedback_criteria_score"
        ),
    )
    op.create_index(
        op.f("ix_feedback_scores_criteria_id"),
        "feedback_scores",
        ["criteria_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedback_scores_feedback_id"),
        "feedback_scores",
        ["feedback_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_feedback_criteria_score", "feedback_scores", type_="unique")

    op.drop_index(op.f("ix_feedback_scores_feedback_id"), table_name="feedback_scores")
    op.drop_index(op.f("ix_feedback_scores_criteria_id"), table_name="feedback_scores")
    op.drop_table("feedback_scores")
    op.drop_index(op.f("ix_feedback_criteria_event_id"), table_name="feedback_criteria")
    op.drop_table("feedback_criteria")
    # ### end Alembic commands ###
