"""Transaction Model: status

Revision ID: 78e5bcf21beb
Revises: 8c4c662dce10
Create Date: 2025-03-14 14:16:49.745604

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from backend.core.constants import PaymentMethodCode

# revision identifiers, used by Alembic.
revision: str = "78e5bcf21beb"
down_revision: Union[str, None] = "8c4c662dce10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

enum_name = PaymentMethodCode.mro()[0].__name__.lower()
enum_keys_to_add = [PaymentMethodCode.FREE.name]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "SUCCESS", "CANCELED", "FAILED", name="transactionstatuscode"
            ),
            autoincrement=False,
            nullable=False,
        ),
    )

    for v in enum_keys_to_add:
        op.execute(f"ALTER TYPE {enum_name} ADD VALUE '{v}'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass


# ### end Alembic commands ###
