"""Update: Cancel Reason Code

Revision ID: 4e605eb9935f
Revises: bc68ba2f6552
Create Date: 2025-03-29 10:07:25.104021

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4e605eb9935f"
down_revision: Union[str, None] = "bc68ba2f6552"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("transaction_items", "cancel_reason_code")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "transaction_items",
        sa.Column(
            "cancel_reason_code",
            postgresql.ENUM(
                "USER_REQUESTED",
                "EVENT_CANCELED",
                "EVENT_RESCHEDULED",
                "DUPLICATE_BOOKING",
                "PAYMENT_FAILED",
                "REFUND_REQUESTED",
                "NO_LONGER_INTERESTED",
                "ILLNESS_OR_EMERGENCY",
                "VENUE_CAPACITY_LIMIT",
                "FRAUDULENT_PURCHASE",
                "ORGANIZER_DISCRETION",
                "VIOLATION_OF_TERMS",
                name="cancelticketreasoncode",
            ),
            autoincrement=False,
            nullable=True,
        ),
    )

    # ### end Alembic commands ###
