"""Organization slug

Revision ID: 1570d6e17ba8
Revises: 4e4116088798
Create Date: 2025-02-15 05:49:52.515745

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1570d6e17ba8"
down_revision: Union[str, None] = "4e4116088798"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("slug", sa.String(length=255), nullable=True)
    )
    op.drop_column("organizations", "representative_url")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column(
            "representative_url",
            sa.VARCHAR(length=2048),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("organizations", "slug")
    # ### end Alembic commands ###
