"""Event: remove comment

Revision ID: 04ad3aa2c234
Revises: 7a40d686c2a4
Create Date: 2025-05-06 16:38:23.855116

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04ad3aa2c234"
down_revision: Union[str, None] = "7a40d686c2a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "comment")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("comment", sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
