"""Event: lng,lng - Ticket: unstrict type

Revision ID: 743f3d470776
Revises: 21fefa8a8582
Create Date: 2025-05-16 04:21:50.897735

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "743f3d470776"
down_revision: Union[str, None] = "21fefa8a8582"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")

    op.add_column(
        "events",
        sa.Column(
            "coordinate",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
    )
    op.add_column("events", sa.Column("lat", sa.DOUBLE_PRECISION(), nullable=True))
    op.add_column("events", sa.Column("lng", sa.DOUBLE_PRECISION(), nullable=True))
    op.create_index(
        "idx_events_coordinate",
        "events",
        ["coordinate"],
        unique=False,
        postgresql_using="gist",
    )

    op.alter_column(
        "tickets",
        "type",
        existing_type=postgresql.ENUM(
            "EARLY_BIRD",
            "VIP",
            "GROUP",
            "CORPORATE",
            "STUDENT",
            "FREE",
            "DONATION",
            "MULTIDAY",
            "DAY_PASS",
            name="tickettypecode",
        ),
        type_=sa.String(length=50),
        existing_nullable=True,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tickets",
        "type",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM(
            "EARLY_BIRD",
            "VIP",
            "GROUP",
            "CORPORATE",
            "STUDENT",
            "FREE",
            "DONATION",
            "MULTIDAY",
            "DAY_PASS",
            name="tickettypecode",
        ),
        existing_nullable=True,
    )
    op.drop_index("idx_events_coordinate", table_name="events", postgresql_using="gist")
    op.drop_column("events", "lng")
    op.drop_column("events", "lat")
    op.drop_column("events", "coordinate")
    # ### end Alembic commands ###
