"""update: feedback model

Revision ID: 5beb679ab998
Revises: 0e69c6562f51
Create Date: 2025-07-04 16:01:16.084363

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5beb679ab998"
down_revision: Union[str, None] = "959464705202"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("is_anonymous", sa.Boolean(), nullable=True))
    op.add_column("events", sa.Column("average_rating", sa.Float(), nullable=True))
    op.alter_column(
        "events",
        "meeting_tool_code",
        existing_type=postgresql.ENUM(
            "ZOOM",
            "GOOGLE_MEET",
            "DISCORD",
            "ROOMINAR",
            "OTHER",
            "CONTACT_LATER",
            name="eventmeetingtoolcode",
        ),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.add_column(
        "feedbacks",
        sa.Column(
            "positive_feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "feedbacks",
        sa.Column(
            "negative_feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column("feedbacks", sa.Column("is_anonymous", sa.Boolean(), nullable=True))
    op.add_column(
        "feedbacks", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_feedbacks_event_id"), "feedbacks", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_feedbacks_user_id"), "feedbacks", ["user_id"], unique=False
    )
    op.create_unique_constraint(
        "uix_event_user_feedback", "feedbacks", ["event_id", "user_id"]
    )
    op.drop_column("feedbacks", "comment")

    op.alter_column(
        "user_actions",
        "device_type",
        existing_type=postgresql.ENUM(
            "DESKTOP", "TABLET", "WEB", "OTHER", "IOS", "ANDROID", name="devicetypecode"
        ),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.add_column("users", sa.Column("point", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "point")

    op.alter_column(
        "user_actions",
        "device_type",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM(
            "DESKTOP", "TABLET", "WEB", "OTHER", "IOS", "ANDROID", name="devicetypecode"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "user_actions",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "speakers", "slug", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.add_column(
        "feedbacks",
        sa.Column("comment", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("uix_event_user_feedback", "feedbacks", type_="unique")
    op.drop_index(op.f("ix_feedbacks_user_id"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_event_id"), table_name="feedbacks")
    op.drop_column("feedbacks", "deleted_at")
    op.drop_column("feedbacks", "is_anonymous")
    op.drop_column("feedbacks", "negative_feedback")
    op.drop_column("feedbacks", "positive_feedback")
    op.alter_column(
        "events",
        "meeting_tool_code",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM(
            "ZOOM",
            "GOOGLE_MEET",
            "DISCORD",
            "ROOMINAR",
            "OTHER",
            "CONTACT_LATER",
            name="eventmeetingtoolcode",
        ),
        existing_nullable=True,
    )
    op.drop_column("events", "average_rating")
    op.drop_column("comments", "is_anonymous")

    # ### end Alembic commands ###
