"""Speaker: Add slug

Revision ID: 21fefa8a8582
Revises: 04ad3aa2c234
Create Date: 2025-05-12 09:03:13.646288

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21fefa8a8582"
down_revision: Union[str, None] = "04ad3aa2c234"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("speakers", sa.Column("slug", sa.String(length=255), nullable=False))
    op.create_index(op.f("ix_speakers_slug"), "speakers", ["slug"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_speakers_slug"), table_name="speakers")
    op.drop_column("speakers", "slug")

    # ### end Alembic commands ###
