"""Comment change vote

Revision ID: 0e69c6562f51
Revises: 7b155b3a84a5
Create Date: 2025-06-28 13:37:48.078857

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e69c6562f51"
down_revision: Union[str, None] = "7b155b3a84a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("comments", sa.Column("vote_count", sa.Integer(), nullable=True))
    op.drop_column("comments", "downvote_count")
    op.drop_column("comments", "upvote_count")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "comments",
        sa.Column("upvote_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "comments",
        sa.Column("downvote_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("comments", "vote_count")

    # ### end Alembic commands ###
