"""Event: update send noti

Revision ID: da4cd1842ca0
Revises: 9ec83f9300e9
Create Date: 2025-06-22 10:03:13.030378

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da4cd1842ca0"
down_revision: Union[str, None] = "9ec83f9300e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("request_feedback_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "events",
        sa.Column(
            "remind_start_before_10m_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "remind_start_before_1d_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "remind_start_before_3d_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "remind_start_before_7d_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "request_feedback_at")
    op.drop_column("events", "remind_start_before_7d_at")
    op.drop_column("events", "remind_start_before_3d_at")
    op.drop_column("events", "remind_start_before_1d_at")
    op.drop_column("events", "remind_start_before_10m_at")
    # ### end Alembic commands ###
