"""Event update statistics

Revision ID: 7b155b3a84a5
Revises: 9d330b34f10e
Create Date: 2025-06-28 03:06:28.647527

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b155b3a84a5"
down_revision: Union[str, None] = "9d330b34f10e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("comment_count", sa.Integer(), nullable=True))
    op.add_column("events", sa.Column("feedback_count", sa.Integer(), nullable=True))
    op.add_column("events", sa.Column("rating_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "rating_count")
    op.drop_column("events", "feedback_count")
    op.drop_column("events", "comment_count")
    # ### end Alembic commands ###
