"""Event: update event statistics fields

Revision ID: feda541acbd6
Revises: da4cd1842ca0
Create Date: 2025-06-22 13:12:08.841033

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "feda541acbd6"
down_revision: Union[str, None] = "da4cd1842ca0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("events", sa.Column("view_count", sa.Integer(), nullable=True))
    op.add_column("events", sa.Column("bookmark_count", sa.Integer(), nullable=True))
    op.add_column("events", sa.Column("sold_ticket_count", sa.Integer(), nullable=True))
    op.add_column("events", sa.Column("share_count", sa.Integer(), nullable=True))
    op.drop_column("events", "view_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "view_count")
    op.drop_column("events", "bookmark_count")
    op.drop_column("events", "sold_ticket_count")
    op.drop_column("events", "share_count")
    op.add_column("events", sa.Column("view_number", sa.Integer(), nullable=True))
    # ### end Alembic commands ###
