"""Tracking Feature New Model: Site Visits and Usr Actions

Revision ID: 7bf1ef9de8c5
Revises: 1570d6e17ba8
Create Date: 2025-03-03 18:24:40.786762

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bf1ef9de8c5"
down_revision: Union[str, None] = "1570d6e17ba8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column(
            "action_type",
            sa.Enum(
                "VIEW",
                "APPLY_EVENT",
                "CANCEL_EVENT",
                "BOOKMARK",
                "SHARE",
                "COMMENT",
                "FOLLOW",
                "RATE",
                "CHECK_IN",
                "CHECK_OUT",
                "REGISTER",
                "LOGIN",
                "LOGOUT",
                "PURCHASE_TICKET",
                "REFUND_TICKET",
                "SEARCH",
                "CLICK",
                "REPORT",
                "DOWNLOAD",
                "UPGRADE_PLAN",
                "WATCH_VIDEO",
                "SUBMIT_SURVEY",
                name="useractiontypecode",
            ),
            nullable=False,
        ),
        sa.Column("extra_info", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "device_type",
            sa.Enum("DESKTOP", "MOBILE", "TABLET", "UNKNOWN", name="devicetypecode"),
            nullable=True,
        ),
        sa.Column(
            "action_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_actions_action_at"), "user_actions", ["action_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_actions_event_id"), "user_actions", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_actions_ip_address"), "user_actions", ["ip_address"], unique=False
    )
    op.create_index(
        op.f("ix_user_actions_organization_id"),
        "user_actions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_actions_user_id"), "user_actions", ["user_id"], unique=False
    )
    op.create_table(
        "site_visits",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "device_type",
            sa.Enum("DESKTOP", "MOBILE", "TABLET", "UNKNOWN", name="devicetypecode"),
            nullable=True,
        ),
        sa.Column(
            "visited_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_site_visits_event_id"), "site_visits", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_site_visits_ip_address"), "site_visits", ["ip_address"], unique=False
    )
    op.create_index(
        op.f("ix_site_visits_organization_id"),
        "site_visits",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_site_visits_visited_at"), "site_visits", ["visited_at"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_site_visits_visited_at"), table_name="site_visits")
    op.drop_index(op.f("ix_site_visits_organization_id"), table_name="site_visits")
    op.drop_index(op.f("ix_site_visits_ip_address"), table_name="site_visits")
    op.drop_index(op.f("ix_site_visits_event_id"), table_name="site_visits")
    op.drop_table("site_visits")
    op.drop_index(op.f("ix_user_actions_user_id"), table_name="user_actions")
    op.drop_index(op.f("ix_user_actions_organization_id"), table_name="user_actions")
    op.drop_index(op.f("ix_user_actions_ip_address"), table_name="user_actions")
    op.drop_index(op.f("ix_user_actions_event_id"), table_name="user_actions")
    op.drop_index(op.f("ix_user_actions_action_at"), table_name="user_actions")
    op.drop_table("user_actions")
    # ### end Alembic commands ###
