"""Notification: add action_url

Revision ID: b0400a0e91d6
Revises: 208a06d4a9e5
Create Date: 2025-04-13 04:31:46.876085

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0400a0e91d6"
down_revision: Union[str, None] = "208a06d4a9e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "events", "id;created_at;updated_at;organization_id;name;start_at;end_at;a"
    )
    op.drop_column("events", "organize_place_name")
    op.add_column("notifications", sa.Column("action_url", sa.String(), nullable=True))
    op.drop_column("tickets", "is_refundable")
    op.drop_column("transactions", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("type", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tickets",
        sa.Column("is_refundable", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ticket_inventories",
        sa.Column(
            "cancelled_quantity", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )

    op.add_column(
        "organizations",
        sa.Column(
            "representative_url",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=True,
        ),
    )

    op.drop_column("notifications", "action_url")
    op.add_column(
        "events",
        sa.Column(
            "organize_place_name",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "id;created_at;updated_at;organization_id;name;start_at;end_at;a",
            sa.VARCHAR(length=2048),
            autoincrement=False,
            nullable=True,
        ),
    )

    # ### end Alembic commands ###
