"""Ticket: refund percentage

Revision ID: bc68ba2f6552
Revises: 4c7f9fd32a0f
Create Date: 2025-03-27 12:52:49.410813

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc68ba2f6552"
down_revision: Union[str, None] = "4c7f9fd32a0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ticket_inventories",
        sa.Column("canceled_quantity", sa.Integer(), nullable=False),
    )
    op.add_column("tickets", sa.Column("refund_percentage", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("tickets", "refund_percentage")
    op.drop_column("ticket_inventories", "canceled_quantity")

    # ### end Alembic commands ###
