"""TransactionItem: Add user_id

Revision ID: 0d0f26a79e7f
Revises: 78e5bcf21beb
Create Date: 2025-03-19 14:53:14.818106

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d0f26a79e7f"
down_revision: Union[str, None] = "78e5bcf21beb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    cancel_reason_code_enum = sa.Enum(
        "USER_REQUESTED",
        "EVENT_CANCELED",
        "EVENT_RESCHEDULED",
        "DUPLICATE_BOOKING",
        "PAYMENT_FAILED",
        "REFUND_REQUESTED",
        "NO_LONGER_INTERESTED",
        "ILLNESS_OR_EMERGENCY",
        "VENUE_CAPACITY_LIMIT",
        "FRAUDULENT_PURCHASE",
        "ORGANIZER_DISCRETION",
        "VIOLATION_OF_TERMS",
        name="cancelticketreasoncode",
    )
    cancel_reason_code_enum.create(op.get_bind())  # Create enum in the database

    op.add_column(
        "transaction_items",
        sa.Column(
            "cancel_reason_code",
            sa.Enum(
                "USER_REQUESTED",
                "EVENT_CANCELED",
                "EVENT_RESCHEDULED",
                "DUPLICATE_BOOKING",
                "PAYMENT_FAILED",
                "REFUND_REQUESTED",
                "NO_LONGER_INTERESTED",
                "ILLNESS_OR_EMERGENCY",
                "VENUE_CAPACITY_LIMIT",
                "FRAUDULENT_PURCHASE",
                "ORGANIZER_DISCRETION",
                "VIOLATION_OF_TERMS",
                name="cancelticketreasoncode",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "transaction_items",
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "transaction_items", sa.Column("user_id", sa.Integer(), nullable=True)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("transaction_items", "user_id")
    op.drop_column("transaction_items", "canceled_at")
    op.drop_column("transaction_items", "cancel_reason_code")

    # ### end Alembic commands ###
