"""Update: Ticket Cancel Fields

Revision ID: 4c7f9fd32a0f
Revises: 0d0f26a79e7f
Create Date: 2025-03-25 15:55:09.883923

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c7f9fd32a0f"
down_revision: Union[str, None] = "0d0f26a79e7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ticket_cancellation_policy_code_enum = sa.Enum(
        "NO_REFUND",
        "FULL_REFUND",
        "PARTIAL_REFUND",
        "REFUND_BY_DATETIME",
        "EXCHANGE_ONLY",
        "NON_TRANSFERABLE",
        "REFUND_IF_EVENT_CANCELED",
        "REFUND_IF_RESCHEDULED",
        "CREDIT_ONLY",
        "THIRD_PARTY_POLICY",
        "INSURANCE_REQUIRED",
        "OTHER",
        name="ticketcancellationpolicycode",
    )
    ticket_cancellation_policy_code_enum.create(
        op.get_bind()
    )  # Create enum in the database

    op.add_column(
        "tickets",
        sa.Column(
            "cancellation_policy_code",
            sa.Enum(
                "NO_REFUND",
                "FULL_REFUND",
                "PARTIAL_REFUND",
                "REFUND_BY_DATETIME",
                "EXCHANGE_ONLY",
                "NON_TRANSFERABLE",
                "REFUND_IF_EVENT_CANCELED",
                "REFUND_IF_RESCHEDULED",
                "CREDIT_ONLY",
                "THIRD_PARTY_POLICY",
                "INSURANCE_REQUIRED",
                "OTHER",
                name="ticketcancellationpolicycode",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "tickets",
        sa.Column(
            "cancellation_policy_extra_description",
            sa.String(length=2048),
            nullable=True,
        ),
    )
    op.add_column(
        "tickets",
        sa.Column("cancelable_before_at", sa.DateTime(timezone=True), nullable=True),
    )

    ticket_refund_method_code_enum = sa.Enum(
        "ORIGINAL_PAYMENT_METHOD",
        "BANK_TRANSFER",
        "EVENT_CREDIT",
        "VOUCHER",
        "THIRD_PARTY_REFUND",
        "CASH",
        "OTHER",
        name="refundmethodcode",
    )
    ticket_refund_method_code_enum.create(op.get_bind())  # Create enum in the database

    op.add_column(
        "tickets",
        sa.Column(
            "refund_method_code",
            sa.Enum(
                "ORIGINAL_PAYMENT_METHOD",
                "BANK_TRANSFER",
                "EVENT_CREDIT",
                "VOUCHER",
                "THIRD_PARTY_REFUND",
                "CASH",
                "OTHER",
                name="refundmethodcode",
            ),
            nullable=True,
        ),
    )
    op.add_column("tickets", sa.Column("cancelation_fee", sa.Float(), nullable=True))
    op.drop_column("tickets", "is_refundable")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tickets",
        sa.Column("is_refundable", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("tickets", "cancelation_fee")
    op.drop_column("tickets", "refund_method_code")
    op.drop_column("tickets", "cancelable_before_at")
    op.drop_column("tickets", "cancellation_policy_extra_description")
    op.drop_column("tickets", "cancellation_policy_code")
    op.drop_column("ticket_inventories", "canceled_quantity")
    # ### end Alembic commands ###
