"""Event: slugify

Revision ID: 0dbb7b3a0a54
Revises: a5070cb82dfd
Create Date: 2025-04-19 04:23:28.987956

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0dbb7b3a0a54"
down_revision: Union[str, None] = "a5070cb82dfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events",
        "slug",
        existing_type=sa.VARCHAR(length=36),
        type_=sa.String(length=255),
        existing_nullable=False,
        existing_server_default=sa.text("gen_random_uuid()"),
    )
    op.create_index(op.f("ix_events_slug"), "events", ["slug"], unique=False)
    op.drop_column("organizations", "representative_url")
    op.drop_column("ticket_inventories", "cancelled_quantity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "ticket_inventories",
        sa.Column(
            "cancelled_quantity", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )

    op.add_column(
        "organizations",
        sa.Column(
            "representative_url",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=True,
        ),
    )

    op.drop_index(op.f("ix_events_slug"), table_name="events")
    op.alter_column(
        "events",
        "slug",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=36),
        existing_nullable=False,
        existing_server_default=sa.text("gen_random_uuid()"),
    )
    # ### end Alembic commands ###
