"""Transaction Model: Update fields

Revision ID: 8c4c662dce10
Revises: 7bf1ef9de8c5
Create Date: 2025-03-13 16:25:01.082265

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8c4c662dce10"
down_revision: Union[str, None] = "7bf1ef9de8c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "applications", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("check_ins", "ticket_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "ticket_inventories", "ticket_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.add_column(
        "transaction_items",
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUCCESS",
                "CANCELED",
                "FAILED",
                "REFUNDED",
                name="transactionstatuscode",
            ),
            nullable=False,
        ),
    )

    payment_method_code_enum = sa.Enum(
        "CREDIT_CARD",
        "PAYPAL",
        "MOMO",
        "ZALOPAY",
        "STRIPE",
        "VNPAY",
        "OTHER",
        name="paymentmethodcode",
    )
    payment_method_code_enum.create(op.get_bind())  # Create enum in the database

    op.add_column(
        "transactions",
        sa.Column(
            "payment_method_code",
            sa.Enum(
                "CREDIT_CARD",
                "PAYPAL",
                "MOMO",
                "ZALOPAY",
                "STRIPE",
                "VNPAY",
                "OTHER",
                name="paymentmethodcode",
            ),
            nullable=False,
        ),
    )

    currency_code_enum = sa.Enum("VND", "USD", "EUR", "JPY", "CNY", name="currencycode")
    currency_code_enum.create(op.get_bind())  # Create enum in the database

    op.add_column(
        "transactions",
        sa.Column(
            "currency",
            sa.Enum("VND", "USD", "EUR", "JPY", "CNY", name="currencycode"),
            nullable=False,
        ),
    )
    op.add_column(
        "transactions", sa.Column("exchange_rate", sa.Float(), nullable=False)
    )
    op.drop_column("transactions", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "type",
            postgresql.ENUM(
                "DONATE",
                "REFUND_CANCEL_TICKET",
                "PURCHASED_TICKET",
                name="transactiontypecode",
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("transactions", "exchange_rate")
    op.drop_column("transactions", "currency")
    op.drop_column("transactions", "payment_method_code")
    op.drop_column("transaction_items", "status")
    op.alter_column(
        "ticket_inventories", "ticket_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "check_ins", "ticket_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "applications", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
