"""Event Model: add new ticket price field

Revision ID: 9ec83f9300e9
Revises: 4f461bc7ad98
Create Date: 2025-06-10 16:51:58.546797

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ec83f9300e9"
down_revision: Union[str, None] = "4f461bc7ad98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("min_ticket_price", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("events", "min_ticket_price")

    # ### end Alembic commands ###
