"""Transaction: Refund Stripe Id

Revision ID: 29558a9605e0
Revises: b0115b35b80d
Create Date: 2025-07-05 13:13:07.805025

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29558a9605e0"
down_revision: Union[str, None] = "b0115b35b80d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("stripe_refund_id", sa.String(255), nullable=True)
    )


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "stripe_refund_id")


# ### end Alembic commands ###
