"""TransactionItem: QrCode

Revision ID: 4f461bc7ad98
Revises: 743f3d470776
Create Date: 2025-05-31 08:25:30.016830

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f461bc7ad98"
down_revision: Union[str, None] = "743f3d470776"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "transaction_items",
        sa.Column("qr_code_id", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "transaction_items",
        sa.Column("qr_code_url", sa.String(length=1024), nullable=True),
    )
    op.create_index(
        op.f("ix_transaction_items_qr_code_id"),
        "transaction_items",
        ["qr_code_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        op.f("ix_transaction_items_qr_code_id"), table_name="transaction_items"
    )
    op.drop_column("transaction_items", "qr_code_url")
    op.drop_column("transaction_items", "qr_code_id")

    # ### end Alembic commands ###
