"""Update: Cancel Reason Code

Revision ID: a2576ce3478d
Revises: 4e605eb9935f
Create Date: 2025-03-29 10:08:32.554901

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a2576ce3478d"
down_revision: Union[str, None] = "4e605eb9935f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    cancel_ticket_reason_code_enum = postgresql.ENUM(
        "EVENT_CANCELED",
        "EVENT_RESCHEDULED",
        "PAYMENT_FAILED",
        "VENUE_CAPACITY_LIMIT",
        "FRAUDULENT_PURCHASE",
        "VIOLATION_OF_TERMS",
        "CHANGE_PLAN",
        "FINANCIAL_ISSUE",
        "PERSONAL_REASON",
        "TIME_CONFLICT",
        "HEALTH_ISSUE",
        "TRANSPORT_ISSUE",
        "PURCHASE_ERROR",
        "NO_COMPANION",
        "VISA_ISSUE",
        "POLICY_ISSUE",
        "BAD_CUSTOMER_SERVICE",
        "WEATHER_ISSUE",
        name="cancelticketreasoncode",
        create_type=False,
    )
    cancel_ticket_reason_code_enum.create(op.get_bind(), checkfirst=False)

    op.add_column(
        "transaction_items",
        sa.Column(
            "cancel_reason_code",
            sa.Enum(
                "EVENT_CANCELED",
                "EVENT_RESCHEDULED",
                "PAYMENT_FAILED",
                "VENUE_CAPACITY_LIMIT",
                "FRAUDULENT_PURCHASE",
                "VIOLATION_OF_TERMS",
                "CHANGE_PLAN",
                "FINANCIAL_ISSUE",
                "PERSONAL_REASON",
                "TIME_CONFLICT",
                "HEALTH_ISSUE",
                "TRANSPORT_ISSUE",
                "PURCHASE_ERROR",
                "NO_COMPANION",
                "VISA_ISSUE",
                "POLICY_ISSUE",
                "BAD_CUSTOMER_SERVICE",
                "WEATHER_ISSUE",
                name="cancelticketreasoncode",
            ),
            nullable=True,
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("transaction_items", "cancel_reason_code")

    # ### end Alembic commands ###
