"""UserNotificationToken: Update device type

Revision ID: 7a40d686c2a4
Revises: 0dbb7b3a0a54
Create Date: 2025-04-20 02:20:27.449523

"""

from typing import Sequence, Union

from alembic import op

from backend.core.constants import DeviceTypeCode

# revision identifiers, used by Alembic.
revision: str = "7a40d686c2a4"
down_revision: Union[str, None] = "0dbb7b3a0a54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

enum_name = DeviceTypeCode.mro()[0].__name__.lower()
enum_keys_to_add = [DeviceTypeCode.IOS.name, DeviceTypeCode.ANDROID.name]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    sql = f"""DELETE FROM pg_enum
            WHERE enumlabel = 'MOBILE'
            AND enumtypid = (
              SELECT oid FROM pg_type WHERE typname = '{enum_name}'
            )"""
    op.execute(sql)

    for v in enum_keys_to_add:
        op.execute(f"ALTER TYPE {enum_name} ADD VALUE '{v}'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for v in enum_keys_to_add:
        sql = f"""DELETE FROM pg_enum
            WHERE enumlabel = '{v}'
            AND enumtypid = (
              SELECT oid FROM pg_type WHERE typname = '{enum_name}'
            )"""
        op.execute(sql)
    # ### end Alembic commands ###
