"""UserAction: Update action_type

Revision ID: aed5a087ceb9
Revises: a2576ce3478d
Create Date: 2025-03-30 03:39:26.457427

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aed5a087ceb9"
down_revision: Union[str, None] = "a2576ce3478d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("user_actions", "action_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_actions",
        sa.Column(
            "action_type",
            postgresql.ENUM(
                "VIEW",
                "APPLY_EVENT",
                "CANCEL_EVENT",
                "BOOKMARK",
                "SHARE",
                "COMMENT",
                "FOLLOW",
                "RATE",
                "CHECK_IN",
                "CHECK_OUT",
                "REGISTER",
                "LOGIN",
                "LOGOUT",
                "PURCHASE_TICKET",
                "REFUND_TICKET",
                "SEARCH",
                "CLICK",
                "REPORT",
                "DOWNLOAD",
                "UPGRADE_PLAN",
                "WATCH_VIDEO",
                "SUBMIT_SURVEY",
                name="useractiontypecode",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )

    # ### end Alembic commands ###
