export const IndustryCodeMapping = {
  REAL_ESTATE: 'Real estate',
  CONSTRUCTION: 'Construction',
  FOOD_DRINK: 'Food & Drink',
  COSMETICS_MANUFACTURING: 'Cosmetics manufacturing',
  ELECTRONICS_MANUFACTURING: 'Electronics manufacturing',
  PRECISION_MANUFACTURING: 'Precision manufacturing',
  AUTOMOTIVE_MANUFACTURING: 'Automotive manufacturing',
  FASHION_MANUFACTURING: 'Fashion manufacturing',
  B2C_MANUFACTURING: 'B2C manufacturing',
  B2B_MANUFACTURING: 'B2B manufacturing',
  LOGISTICS: 'Logistics',
  IT_COMMUNICATIONS: 'IT & Communications',
  CONTRACT_DEVELOPMENT: 'Contract development',
  RETAIL: 'Retail',
  WHOLESALE: 'Wholesale',
  FINANCE: 'Finance',
  HOSPITALITY: 'Hospitality',
  CONSULTING: 'Consulting',
  HEALTHCARE: 'Healthcare',
  ADVERTISING: 'Advertising',
  ENTERTAINMENT: 'Entertainment',
  EDUCATION: 'Education',
  MEDIA: 'Media',
  MINING: 'Mining',
  TRANSPORTATION: 'Transportation',
  WAREHOUSING: 'Warehousing',
  CHEMICAL: 'Chemical',
  OTHER: 'Other',
};

export const JobTypeCodeMapping = {
  DEV: 'Developer',
  QA: 'Quality Assurance',
  PM: 'Project Manager',
  TESTER: 'Tester',
  SYSADMIN: 'System Administrator',
  DBA: 'Database Administrator',
  SA: 'Solution Architect',
  ACC: 'Accountant',
  FIN: 'Financial Analyst',
  CFA: 'Certified Financial Analyst',
  TAX: 'Tax Consultant',
  AUD: 'Auditor',
  SEO: 'Search Engine Optimization Specialist',
  SMM: 'Social Media Manager',
  PR: 'Public Relations Specialist',
  AD: 'Advertising Manager',
  CMM: 'Content Marketing',
  TEACHER: 'Teacher',
  LECTURER: 'Lecturer',
  TUTOR: 'Tutor',
  PRINCIPAL: 'Principal',
  COUNSELOR: 'School Counselor',
  DOCTOR: 'Doctor',
  NURSE: 'Nurse',
  PHARM: 'Pharmacist',
  SURGEON: 'Surgeon',
  THER: 'Therapist',
  ARCH: 'Architect',
  ENG: 'Engineer',
  CIVIL: 'Civil Engineer',
  CON: 'Contractor',
  QS: 'Quantity Surveyor',
  DESIGNER: 'Designer',
  ARTIST: 'Artist',
  WRITER: 'Writer',
  MUSICIAN: 'Musician',
  ACTOR: 'Actor',
  CS: 'Customer Service Representative',
  SALES: 'Salesperson',
  CRM: 'Customer Relationship Manager',
  CASHIER: 'Cashier',
  MERCH: 'Merchandiser',
  DRIVER: 'Driver',
  LOG: 'Logistician',
  WAREHOUSE: 'Warehouse Manager',
  SHIP: 'Shipping Coordinator',
  FARMER: 'Farmer',
  AGR: 'Agricultural Engineer',
  VET: 'Veterinarian',
  HORT: 'Horticulturist',
};

export const EventSortByCodeMappings = {
  START_AT: 'Upcoming',
  PUBLISHED_AT: 'Recently Public',
  APPLICATION_END_AT: 'Deadline',
  RECOMMEDATION: 'Recommendation',
};

export const EventMeetingToolCodeMappings = {
  ZOOM: 'Zoom',
  MEET: 'Google Meet',
  DISCORD: 'Discord',
  OTHER: 'Other',
  CONTACT_LATER: 'Contact later',
};

export const CityCodeMappings = {
  HANOI: 'Hà Nội',
  HOCHIMINH: 'Hồ Chí Minh',
  DANANG: 'Đà Nẵng',
  HAIPHONG: 'Hải Phòng',
  CANTHO: 'Cần Thơ',
  ANGIANG: 'An Giang',
  BACGIANG: 'Bắc Giang',
  BACKAN: 'Bắc Kạn',
  BACLIEU: 'Bạc Liêu',
  BACNINH: 'Bắc Ninh',
  BARIAVUNGTAU: 'Bà Rịa - Vũng Tàu',
  BENTRE: 'Bến Tre',
  BINHDINH: 'Bình Định',
  BINHDUONG: 'Bình Dương',
  BINHPHUOC: 'Bình Phước',
  BINHTHUAN: 'Bình Thuận',
  CAOBANG: 'Cao Bằng',
  DAKLAK: 'Đắk Lắk',
  DAKNONG: 'Đắk Nông',
  DIENBIEN: 'Điện Biên',
  DONGNAI: 'Đồng Nai',
  DONGTHAP: 'Đồng Tháp',
  GIALAI: 'Gia Lai',
  HAGIANG: 'Hà Giang',
  HATINH: 'Hà Tĩnh',
  HAUGIANG: 'Hậu Giang',
  HOABINH: 'Hòa Bình',
  HUNGYEN: 'Hưng Yên',
  KHANHHOA: 'Khánh Hòa',
  KIENGIANG: 'Kiên Giang',
  KONTUM: 'Kon Tum',
  LAICHAU: 'Lai Châu',
  LAMDONG: 'Lâm Đồng',
  LANGSON: 'Lạng Sơn',
  LAOCAI: 'Lào Cai',
  LONGAN: 'Long An',
  NAMDINH: 'Nam Định',
  NGHEAN: 'Nghệ An',
  NINHBINH: 'Ninh Bình',
  NINHTHUAN: 'Ninh Thuận',
  PHUTHO: 'Phú Thọ',
  PHUYEN: 'Phú Yên',
  QUANGBINH: 'Quảng Bình',
  QUANGNAM: 'Quảng Nam',
  QUANGNGAI: 'Quảng Ngãi',
  QUANGNINH: 'Quảng Ninh',
  QUANGTRI: 'Quảng Trị',
  SOCTRANG: 'Sóc Trăng',
  SONLA: 'Sơn La',
  TAYNINH: 'Tây Ninh',
  THAIBINH: 'Thái Bình',
  THAINGUYEN: 'Thái Nguyên',
  THANHHOA: 'Thanh Hóa',
  THUATHIENHUE: 'Thừa Thiên Huế',
  TIENGIANG: 'Tiền Giang',
  TRAVINH: 'Trà Vinh',
  TUYENQUANG: 'Tuyên Quang',
  VINHLONG: 'Vĩnh Long',
  VINHPHUC: 'Vĩnh Phúc',
  YENBAI: 'Yên Bái',
};

export const QuestionTypeCodeMappings = {
  SINGLE: 'Single',
  MULTIPLE: 'Multiple',
  TEXT: 'Text',
};
