export const JobTypeCodeMapping = {
  DEV: 'Developer',
  QA: 'Quality Assurance',
  PM: 'Project Manager',
  TESTER: 'Tester',
  SYSADMIN: 'System Administrator',
  DBA: 'Database Administrator',
  SA: 'Solution Architect',
  ACC: 'Accountant',
  FIN: 'Financial Analyst',
  CFA: 'Certified Financial Analyst',
  TAX: 'Tax Consultant',
  AUD: 'Auditor',
  SEO: 'Search Engine Optimization Specialist',
  SMM: 'Social Media Manager',
  PR: 'Public Relations Specialist',
  AD: 'Advertising Manager',
  CMM: 'Content Marketing',
  TEACHER: 'Teacher',
  LECTURER: 'Lecturer',
  TUTOR: 'Tutor',
  PRINCIPAL: 'Principal',
  COUNSELOR: 'School Counselor',
  DOCTOR: 'Doctor',
  NURSE: 'Nurse',
  PHARM: 'Pharmacist',
  SURGEON: 'Surgeon',
  THER: 'Therapist',
  ARCH: 'Architect',
  ENG: 'Engineer',
  CIVIL: 'Civil Engineer',
  CON: 'Contractor',
  QS: 'Quantity Surveyor',
  DESIGNER: 'Designer',
  ARTIST: 'Artist',
  WRITER: 'Writer',
  MUSICIAN: 'Musician',
  ACTOR: 'Actor',
  CS: 'Customer Service Representative',
  SALES: 'Salesperson',
  CRM: 'Customer Relationship Manager',
  CASHIER: 'Cashier',
  MERCH: 'Merchandiser',
  DRIVER: 'Driver',
  LOG: 'Logistician',
  WAREHOUSE: 'Warehouse Manager',
  SHIP: 'Shipping Coordinator',
  FARMER: 'Farmer',
  AGR: 'Agricultural Engineer',
  VET: 'Veterinarian',
  HORT: 'Horticulturist',
};
